### PR TITLE
[jdbc-v2] Fixed getting database metadata

### LINKED ISSUE #2282: [jdbc-v2] Error while getting type information from DataBaseMetadata
### Describe the bug

Error: 
```
ava.lang.IllegalArgumentException: Missing function parameters
  at com.clickhouse.data.ClickHouseColumn.readColumn(ClickHouseColumn.java:338)
  at com.clickhouse.data.ClickHouseColumn.parse(ClickHouseColumn.java:627)
  at com.clickhouse.jdbc.internal.MetadataResultSet.getString(MetadataResultSet.java:22)
  at com.clickhouse.jdbc.internal.MetadataResultSet.getInt(MetadataResultSet.java:31)
```

### Steps to reproduce
1. Create connection
2. get metadata by calling `java.sql.Connection#getMetaData` 
3. call `java.sql.DatabaseMetaData#getTypeInfo` then 

Similar issue with `getColumns()`

### PR DESCRIPTION
**Pull request by chernser**
## Summary
- Fixes problem with data type name conversion in `DatabaseMetaData`. 
- Fixes problem with missing LZ4 library in shaded jars 

Closes https://github.com/ClickHouse/clickhouse-java/issues/2282
## Checklist
Delete items not relevant to your PR:
- [x] Closes #2282 
- [x] Unit and integration tests covering the common scenarios were added
- [ ] A human-readable description of the changes was provided to include in CHANGELOG
- [ ] For significant changes, documentation in https://github.com/ClickHouse/clickhouse-docs was updated with further explanations or tutorials

### CODE REVIEW

**Comment by mshustov** [comment]
@chernser does it close https://github.com/ClickHouse/clickhouse-java/issues/2282 ?

File: jdbc-v2/src/main/java/com/clickhouse/jdbc/internal/JdbcUtils.java [hunk 1]
```diff
@@ -15,16 +16,27 @@
 import java.time.ZonedDateTime;
 import java.time.temporal.TemporalAccessor;
 import java.util.ArrayList;
+import java.util.Collections;
 import java.util.HashMap;
 import java.util.List;
 import java.util.Map;
+import java.util.Optional;
```
Comment (mzitnik) [inline jdbc-v2/src/main/java/com/clickhouse/jdbc/internal/JdbcUtils.java:23]: Do we use it?

File: clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/ClickHouseDatabaseMetaDataTest.java [hunk 2]
```diff
@@ -96,7 +96,9 @@ public void testGetTypeInfo() throws SQLException {
         props.setProperty("decompress", "0");
         try (ClickHouseConnection conn = newConnection(props); ResultSet rs = conn.getMetaData().getTypeInfo()) {
             while (rs.next()) {
-                Assert.assertNotNull(rs.getString(1));
+                rs.getString(1);
```
Comment (mzitnik) [inline clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/ClickHouseDatabaseMetaDataTest.java:99]: Should we also Assert this?

Comment (chernser) [reply clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/ClickHouseDatabaseMetaDataTest.java:99]: will revert - it is an old code and I've made change to debug
