### PR TITLE
Issue 2118

### LINKED ISSUE #2118: client.insert(...) fails if registered class doesn't match all existing columns
### Describe the bug
Attempting an `insert` fails if any column from the target table is not defined in the registered POJO.

### Steps to reproduce
1. Register a POJO associated with any given table. The table should contain at least one additional column that is **not** defined in the POJO.
2. Attempt to call `client.insert(...)` for one of these POJO instances.
3. Receive an `IllegalArgumentException` (`No serializer found for column 'example'. Did you forget to register it?`).

From my understanding, the problem comes from the fact that `client.insert(...)` assumes the resulting `INSERT` command should include values for all existing columns (which should not be the case), throwing an exception in line 1350 of `com.clickhouse.client.api.Client` when this is not the case.

### Expected behaviour
`client.insert(...)` should ideally work even if the registered class is 'missing' some columns from the mapped table. While this can be partially solved by just adding said missing column into the registered class, this particular behavior can be problematic in certain cases

For example, when adding a new column to an existing table, this would theoretically break the mapping of the version running in production - which would not have the corresponding attribute in the POJO class.

### Error log
```
java.lang.IllegalArgumentException: No serializer found for column 'example'. Did you forget to register it?
	at com.clickhouse.client.api.Client.insert(Client.java:1350)
```

Thanks in advance for reading this!

### PR DESCRIPTION
**Pull request by mzitnik**
This pull request introduces support for handling default values in ClickHouse columns, including `MATERIALIZED`, `ALIAS`, and `EPHEMERAL` types. It adds new functionality to skip these columns during data insertion and ensures proper parsing and testing of default expressions. The most important changes are grouped below:

### Enhancements to `ClickHouseColumn` class:

* Added a new `DefaultValue` enum to represent different default types (`DEFAULT`, `MATERIALIZED`, `EPHEMERAL`, `ALIAS`) and associated fields `defaultValue` and `defaultExpression` to the `ClickHouseColumn` class.
* Introduced getter and setter methods for `defaultValue` and `defaultExpression` in the `ClickHouseColumn` class.

### Changes to data insertion logic:

* Updated the `insert` method in `Client.java` to skip columns with default values other than `DEFAULT` during data insertion.
* Modified the `commitRow` method in `RowBinaryFormatWriter.java` to similarly skip columns with `MATERIALIZED`, `ALIAS`, or other non-default values.

### Schema parsing improvements:

* Enhanced `TableSchemaParser` to parse `default_type` and `default_expression` properties from table schema and set them in `ClickHouseColumn`.

### New test cases:

* Added a test case `testWriterWithMaterialize` to validate insertion behavior with columns having various default types (`MATERIALIZED`, `ALIAS`, `EPHEMERAL`).
* Introduced `insertSimplePOJOsWithMaterializeColumn` test to verify POJO insertion with `MATERIALIZED` and `ALIAS` columns.

### Additional utility class:

* Added `SimplePOJO` class with a method to generate table creation SQL for testing columns with default values and default expressions.## Summary

Closes #2118 #2025 
## Checklist
Delete items not relevant to your PR:
- [X] Closes #2118 #2025
- [X] Unit and integration tests covering the common scenarios were added
- [ ] A human-readable description of the changes was provided to include in CHANGELOG
- [ ] For significant changes, documentation in https://github.com/ClickHouse/clickhouse-docs was updated with further explanations or tutorials

### CODE REVIEW

File: clickhouse-data/src/main/java/com/clickhouse/data/ClickHouseColumn.java [hunk 1]
```diff
@@ -106,6 +106,21 @@ public final class ClickHouseColumn implements Serializable {
     private Map<Class<?>, Integer> mapKeyToVariantOrdNumMap;
     private Map<Class<?>, Integer> mapValueToVariantOrdNumMap;
 
+    public enum DefaultValue {
+        DEFAULT("Default"),
+        MATERIALIZED("MATERIALIZED"),
```
Comment (chernser) [inline clickhouse-data/src/main/java/com/clickhouse/data/ClickHouseColumn.java:111]: Should it be like Default - "Materialized" ?

File: clickhouse-data/src/main/java/com/clickhouse/data/ClickHouseColumn.java [hunk 2]
```diff
@@ -106,6 +106,21 @@ public final class ClickHouseColumn implements Serializable {
...
+        EPHEMERAL("EPHEMERAL"),
+        ALIAS("ALIAS");
+
+        public final String defaultValue;
```
Comment (chernser) [inline clickhouse-data/src/main/java/com/clickhouse/data/ClickHouseColumn.java:115]: May be lets rename it to `kind` or `type` just to avoid too many `defaultValue` in one place?

File: clickhouse-data/src/main/java/com/clickhouse/data/ClickHouseColumn.java (hunk 1 above)
Comment (mzitnik) [reply clickhouse-data/src/main/java/com/clickhouse/data/ClickHouseColumn.java:111]: According to https://clickhouse.com/docs/sql-reference/statements/create/table#default_values all are `DefaultValue`

**Review by chernser — APPROVED** [review]

File: clickhouse-data/src/main/java/com/clickhouse/data/ClickHouseColumn.java (hunk 2 above)
Comment (mzitnik) [reply clickhouse-data/src/main/java/com/clickhouse/data/ClickHouseColumn.java:115]: See my last comment, I prefer to stick with ClickHouse documentation language
