### PR TITLE
fix: #2132 fix executing queries with 'WITH' clause in jdbc v2

### LINKED ISSUE #2132: jdbc-v2  Common Table Expression  query ResultSet is null
version 0.8.0

### Code example
```java
    @Test
    void testV2With() {
        Properties properties = new Properties();
        properties.setProperty("user", "****");
        properties.setProperty("password", "****");
        List<Integer> list = new ArrayList<>();
        try (Connection conn = DriverManager.getConnection("jdbc:clickhouse://localhost:8123/default", properties)) {
            try (PreparedStatement stmt = conn.prepareStatement("""
                    with data as (SELECT number
                                  FROM numbers(100))
                    select *
                    from data
                    """)) {
                stmt.execute();
                ResultSet rs = stmt.getResultSet();
                while (rs.next()) {
                    list.add(rs.getInt(1));
                }
            }
        }
        assertEquals(100, list.size());
    }

```
### Error log

```
java.lang.NullPointerException: Cannot invoke "java.sql.ResultSet.next()" because "rs" is null
```

### PR DESCRIPTION
**Pull request by samssh**
## Summary

The issue seemed to be in the `parseStatementType` function. I have also added several tests related to this scenario.
Closes #2132 

## Checklist
- [x] Closes #2132
- [x] Unit and integration tests covering the common scenarios were added
- [ ] A human-readable description of the changes was provided to include in CHANGELOG

I'm not sure what to do regarding the changelog. If there's any action required, please guide me. Thank you for your help!

### CODE REVIEW

File: jdbc-v2/src/test/java/com/clickhouse/jdbc/StatementTest.java [hunk 1]
```diff
@@ -539,4 +544,20 @@ public void testTextFormatInResponse() throws Exception {
...
+
+    @Test(groups = "integration")
+    void testWithClause() throws Exception {
+        int count = 0;
+        try (Connection conn = getJdbcConnection()) {
+            try (Statement stmt = conn.createStatement()) {
+                stmt.execute("with data as (SELECT number FROM numbers(100)) select * from data");
+                ResultSet rs = stmt.getResultSet();
+                while (rs.next()) {
+                    System.out.println(rs.getInt(1));
```
Comment (mzitnik) [inline jdbc-v2/src/test/java/com/clickhouse/jdbc/StatementTest.java:556]: Lets remove or change into logger all the relevant places

**Review by mzitnik — CHANGES_REQUESTED** [review]

File: jdbc-v2/src/test/java/com/clickhouse/jdbc/StatementTest.java (hunk 1 above)
Comment (samssh) [reply jdbc-v2/src/test/java/com/clickhouse/jdbc/StatementTest.java:556]: it used for debug and should be removed.

**Comment by samssh** [comment]
It seems that several tests have failed, but they do not appear to be related to my changes.

**Review by chernser — APPROVED** [review]

**Comment by chernser** [comment]
@samssh thank you!
