### PR TITLE
fix logging

### LINKED ISSUE #1571: Clickhouse JDBC driver logging passwords in plain text.
### Describe the bug
Not quite a bug however can be a security issue. The jdbc driver is logging passwords in plain text. 

### Steps to reproduce
1. Log at debug level
2. Make a connection via clickhouse jdbc driver (I am using it in flyway)

### Expected behaviour
user credentials should not be logged. unless set to do so explicitly 

### Error log
```


{"logger":"com.clickhouse.client.http.ClickHouseHttpConnectionFactory","level":"WARN","message":"Error when creating APACHE_HTTP_CLIENT, fall back to HTTP_URL_CONNECTION"}
{"logger":"com.clickhouse.client.http.ClickHouseHttpConnection","level":"DEBUG","message":"url [http://clickhouse-release:8123/?compress=1&extremes=0]"}
{"logger":"com.clickhouse.client.AbstractClient","level":"DEBUG","message":"Connection established: com.clickhouse.client.http.HttpUrlConnectionImpl@65ae095c"}
{"logger":"com.clickhouse.client.http.ClickHouseHttpClient","level":"DEBUG","message":"Query: select 1"}
{"logger":"com.clickhouse.client.http.HttpUrlConnectionImpl","level":"DEBUG","message":"Adding header key [accept] value [*/*]"}
{"logger":"com.clickhouse.client.http.HttpUrlConnectionImpl","level":"DEBUG","message":"Adding header key [user-agent] value [ClickHouse-JdbcDriver/unknown (Linux/6.2.0-1012-aws; OpenJDK 64-Bit Server VM/Temurin-21.0.2+13; HttpURLConnection; rv:unknown)]"}
{"logger":"com.clickhouse.client.http.HttpUrlConnectionImpl","level":"DEBUG","message":"Adding header key [x-clickhouse-user] value [my user]"}
{"logger":"com.clickhouse.client.http.HttpUrlConnectionImpl","level":"DEBUG","message":"Adding header key [x-clickhouse-key] value [my password]"}
{"logger":"com.clickhouse.client.http.HttpUrlConnectionImpl","level":"DEBUG","message":"Adding header key [x-clickhouse-database] value [my user name]"}
{"logger":"com.clickhouse.client.http.HttpUrlConnectionImpl","level":"DEBUG","message":"Adding header key [x-clickhouse-format] value [RowBinaryWithNamesAndTypes]"}
{"logger":"com.clickhouse.client.http.HttpUrlConnectionImpl","level":"DEBUG","message":"Adding header key [accept-encoding] value [lz4]"}
{"logger":"com.clickhouse.client.http.HttpUrlConnectionImpl","level":"DEBUG","message":"http response code [200]"}
{"logger":"com.clickhouse.client.ClickHouseStreamResponse","level":"DEBUG","message":"10 bytes skipped before closing input stream"}
{"logger":"org.flywaydb.core.FlywayExecutor","level":"DEBUG","message":"Memory usage: 15 of 24M"}
```

### PR DESCRIPTION
**Pull request by chernser**
## Summary
Closes https://github.com/ClickHouse/clickhouse-java/issues/1571

### CODE REVIEW

File: clickhouse-http-client/src/main/java/com/clickhouse/client/http/HttpUrlConnectionImpl.java [hunk 1]
```diff
@@ -146,12 +149,21 @@ private String getResponseHeader(String header, String defaultValue) {
...
+    private static final Set<String> maskedHeaders = new HashSet<>(Arrays.asList("authorization",
+            "proxy-authorization","x-clickhouse-key"));
+
     private void setHeaders(HttpURLConnection conn, Map<String, String> headers) {
         headers = mergeHeaders(headers);
 
         if (headers != null && !headers.isEmpty()) {
             for (Entry<String, String> header : headers.entrySet()) {
-                log.debug("Adding header key [%s] value [%s]", header.getKey(), header.getValue());
+                if (log.isDebugEnabled()) {
```
Comment (mzitnik) [inline clickhouse-http-client/src/main/java/com/clickhouse/client/http/HttpUrlConnectionImpl.java:160]: It is not such a big issue, but headers are a map, and we are converting them to set so we iterate on all the headers that we have (size N) instead of iterating on maskHeders set (size M=2) and only to check if we have the header O(1) get operation of a map maskedHeaders so I think in this case the search should be in size of the maskHeders list.

**Review by mzitnik — APPROVED** [review]
