### PR TITLE
Fixes and improvements for multiple problems of jdbc_v2 and client_v2

### LINKED ISSUE #2292: [jdbc-v2] Prepared statement metadata returns null
### Description 

When `com.clickhouse.jdbc.PreparedStatementImpl#getMetaData` called it returns `null`

Expected behavior: return metadata for the prepared statement.

### PR DESCRIPTION
**Pull request by oleg-zinovev**
## Summary

Contains several improvements and fixes for the v2 of the client and driver

Improvements: 
- PreparedStatementImpl: getMetaData returns result set metadata using describe query
- StatementImpl: maxRows handling
- Driver: unload method fixed (DriverManager search driver for unregister by reference equality)
- HttpAPIClientHelper: added sslmode option (presents in v1), support to skip ssl validation 

Fixes:
 - PreparedStatementImpl: ignores question mark (?) in comments, string literals and quoted identifiers
 - StatementImpl: multiline block comments trim
 - HttpAPIClientHelper: null pointer exception with unpooled connection (poolControl is null)

Closes #2292, #2290
## Checklist
Delete items not relevant to your PR:
- [x] Closes #2292, #2290
- [x] Unit and integration tests covering the common scenarios were added
- [ ] A human-readable description of the changes was provided to include in CHANGELOG
- [ ] For significant changes, documentation in https://github.com/ClickHouse/clickhouse-docs was updated with further explanations or tutorials

### CODE REVIEW

File: client-v2/src/main/java/com/clickhouse/client/api/ClientConfigProperties.java [hunk 1]
```diff
@@ -92,6 +92,8 @@ public enum ClientConfigProperties {
 
     SSL_KEY_STORE_PASSWORD("key_store_password"),
 
+    SSL_MODE("sslmode", "strict", Arrays.asList("strict", "none")),
```
Comment (chernser) [inline client-v2/src/main/java/com/clickhouse/client/api/ClientConfigProperties.java:95]: How would this parameter work? Just toggle support of SSL? 
How would it work when `https` endpoint is set and `sslmode=none` ?

File: client-v2/src/main/java/com/clickhouse/client/api/internal/HttpAPIClientHelper.java [hunk 2]
```diff
@@ -169,6 +175,13 @@ public SSLContext createSSLContext() {
             } catch (SSLException e) {
                 throw new ClientMisconfigurationException("Failed to create SSL context from certificates", e);
             }
+        } else if ("none".equals(chConfiguration.get(ClientConfigProperties.SSL_MODE.getKey()))) {
+            try {
+                sslContext = SSLContext.getInstance("TLS");
```
Comment (chernser) [inline client-v2/src/main/java/com/clickhouse/client/api/internal/HttpAPIClientHelper.java:180]: Here you are going to initialize a sslContex, but ssl mode is "none" and no-one seems will use HTTPs then. Do we need initialize it anyway for some case?

File: client-v2/src/test/java/com/clickhouse/client/ClientTests.java [hunk 3]
```diff
@@ -64,6 +65,12 @@ private static Client[] secureClientProvider() throws Exception {
                         .setPassword("")
                         .setRootCertificate("containers/clickhouse-server/certs/localhost.crt")
                         .build(),
+                new Client.Builder()
```
Comment (chernser) [inline client-v2/src/test/java/com/clickhouse/client/ClientTests.java:68]: In what case this is used?

File: jdbc-v2/src/main/java/com/clickhouse/jdbc/Driver.java [hunk 4]
```diff
@@ -163,4 +163,8 @@ public static String chSettingKey(String key) {
     public java.util.logging.Logger getParentLogger() throws SQLFeatureNotSupportedException {
         throw new SQLFeatureNotSupportedException("Method not supported", ExceptionUtils.SQL_STATE_FEATURE_NOT_SUPPORTED);
     }
+
+    private static final class DriverHolder {
```
Comment (chernser) [inline jdbc-v2/src/main/java/com/clickhouse/jdbc/Driver.java:167]: I think, we do not need this wrapper class. or do we?

File: jdbc-v2/src/main/java/com/clickhouse/jdbc/PreparedStatementImpl.java [hunk 5]
```diff
@@ -305,7 +303,26 @@ public void setArray(int parameterIndex, Array x) throws SQLException {
     @Override
     public ResultSetMetaData getMetaData() throws SQLException {
         checkClosed();
-        return null;
+        if (this.currentResultSet != null) {
+            return currentResultSet.getMetaData();
+        } else if (statementType != StatementType.SELECT) {
+            return null;
```
Comment (chernser) [inline jdbc-v2/src/main/java/com/clickhouse/jdbc/PreparedStatementImpl.java:309]: Should it return an empty result set? 
I think, null is not expected.

File: jdbc-v2/src/main/java/com/clickhouse/jdbc/PreparedStatementImpl.java [hunk 6]
```diff
@@ -305,7 +303,26 @@ public void setArray(int parameterIndex, Array x) throws SQLException {
...
+        }
+
+        String sql = compileSql(sqlSegments);
+        String describe = String.format("describe (\n%s\n)", sql);
```
Comment (chernser) [inline jdbc-v2/src/main/java/com/clickhouse/jdbc/PreparedStatementImpl.java:313]: This is already implemented in `com.clickhouse.client.api.Client#getTableSchemaFromQuery(java.lang.String)`

**Comment by chernser** [comment]
@oleg-zinovev thank you for the contribution! 
Would you please exclude: 
- PreparedStatementImpl: getMetaData returns result set metadata using describe query - I'm working on it and have a bigger change to support more cases 
- HttpAPIClientHelper: added sslmode option (presents in v1), support to skip ssl validation - We need to discuss this because why to exclude ssl validation when you do not use it. In other cases we need to support self signed certificates but need another way to do so. 

Thanks!

File: client-v2/src/main/java/com/clickhouse/client/api/ClientConfigProperties.java (hunk 1 above)
Comment (oleg-zinovev) [reply client-v2/src/main/java/com/clickhouse/client/api/ClientConfigProperties.java:95]: Behavior is completely identical to the v1 version of client:
- sslmode=none disables server certificate validation

You can see v1 code here: com/clickhouse/client/config/ClickHouseDefaultSslContextProvider.java:151

File: client-v2/src/main/java/com/clickhouse/client/api/internal/HttpAPIClientHelper.java (hunk 2 above)
Comment (oleg-zinovev) [reply client-v2/src/main/java/com/clickhouse/client/api/internal/HttpAPIClientHelper.java:180]: https://clickhouse.com/docs/integrations/language-clients/java/jdbc-v1#ssl-properties

According to this doc, sslmode means 'Whether to verify SSL/TLS certificate'

File: client-v2/src/test/java/com/clickhouse/client/ClientTests.java (hunk 3 above)
Comment (oleg-zinovev) [reply client-v2/src/test/java/com/clickhouse/client/ClientTests.java:68]: This code adds testing of https connection with disabled SSL certificate validation.

Configured clients used in the testAddSecureEndpoint test.

File: jdbc-v2/src/main/java/com/clickhouse/jdbc/PreparedStatementImpl.java (hunk 5 above)
Comment (oleg-zinovev) [reply jdbc-v2/src/main/java/com/clickhouse/jdbc/PreparedStatementImpl.java:309]: Null is expected according to PreparedStatement javadoc:

` * @return the description of a {@code ResultSet} object's columns or
     *         {@code null} if the driver cannot return a
     *         {@code ResultSetMetaData} object`

**Comment by oleg-zinovev** [comment]
> @oleg-zinovev thank you for the contribution! Would you please exclude:

> * HttpAPIClientHelper: added sslmode option (presents in v1), support to skip ssl validation - We need to discuss this because why to exclude ssl validation when you do not use it. In other cases we need to support self signed certificates but need another way to do so.
> 
> Thanks!


An example of using the ssl mode in our case:

sslmode is convenient for DBeaver (and similar programs). It is much easier (in the case of a self-signed certificate) to disable its verification than to explain how to specify the server certificate correctly.
Unfortunately, in our case, the use of endpoints without encryption is prohibited.

File: client-v2/src/main/java/com/clickhouse/client/api/ClientConfigProperties.java (hunk 1 above)
Comment (oleg-zinovev) [reply client-v2/src/main/java/com/clickhouse/client/api/ClientConfigProperties.java]: @chernser Removed

File: client-v2/src/main/java/com/clickhouse/client/api/internal/HttpAPIClientHelper.java (hunk 2 above)
Comment (oleg-zinovev) [reply client-v2/src/main/java/com/clickhouse/client/api/internal/HttpAPIClientHelper.java]: @chernser Removed

File: jdbc-v2/src/main/java/com/clickhouse/jdbc/Driver.java (hunk 4 above)
Comment (oleg-zinovev) [reply jdbc-v2/src/main/java/com/clickhouse/jdbc/Driver.java]: @chernser Removed

File: jdbc-v2/src/main/java/com/clickhouse/jdbc/PreparedStatementImpl.java (hunk 5 above)
Comment (oleg-zinovev) [reply jdbc-v2/src/main/java/com/clickhouse/jdbc/PreparedStatementImpl.java]: @chernser Removed

File: jdbc-v2/src/main/java/com/clickhouse/jdbc/PreparedStatementImpl.java [hunk 7]
```diff
@@ -305,7 +303,26 @@ public void setArray(int parameterIndex, Array x) throws SQLException {
     @Override
     public ResultSetMetaData getMetaData() throws SQLException {
         checkClosed();
-        return null;
+        if (this.currentResultSet != null) {
+            return currentResultSet.getMetaData();
+        } else if (statementType != StatementType.SELECT) {
```
[the remark this answers is not in the document]
Comment (oleg-zinovev) [reply jdbc-v2/src/main/java/com/clickhouse/jdbc/PreparedStatementImpl.java]: @chernser Removed

File: jdbc-v2/src/main/java/com/clickhouse/jdbc/PreparedStatementImpl.java (hunk 6 above)
Comment (oleg-zinovev) [reply jdbc-v2/src/main/java/com/clickhouse/jdbc/PreparedStatementImpl.java]: @chernser Removed

File: jdbc-v2/src/main/java/com/clickhouse/jdbc/PreparedStatementImpl.java (hunk 5 above)
Comment (chernser) [reply jdbc-v2/src/main/java/com/clickhouse/jdbc/PreparedStatementImpl.java]: Thank you! 

I agree that specification allows to return null, but some frameworks doesn't accept it so we need to implement this another way - at least return an empty result set.

File: jdbc-v2/src/main/java/com/clickhouse/jdbc/Driver.java (hunk 4 above)
Comment (chernser) [reply jdbc-v2/src/main/java/com/clickhouse/jdbc/Driver.java]: Thank you!

File: client-v2/src/main/java/com/clickhouse/client/api/internal/HttpAPIClientHelper.java (hunk 2 above)
Comment (chernser) [reply client-v2/src/main/java/com/clickhouse/client/api/internal/HttpAPIClientHelper.java]: As I've mentioned we will port this feature with some changes. 
Thanks!

File: client-v2/src/main/java/com/clickhouse/client/api/ClientConfigProperties.java (hunk 1 above)
Comment (chernser) [reply client-v2/src/main/java/com/clickhouse/client/api/ClientConfigProperties.java]: Thank you!

**Review by chernser — APPROVED** [review]

**Comment by chernser** [comment]
@oleg-zinovev thank you for the update! 
I've run CI and will approve shortly. 

As for SSL strict mode I've created a separate issue https://github.com/ClickHouse/clickhouse-java/issues/2309 
I would like implement it in the way:
- It doesn't confuses users with configuration. SSL mode can be theoretically applied to SSL auth and may be need to have another configuration 
- User may need more configuration over SSL (we had a request for custom SSL factory) 
So yes, we will work on it.
