### PR TITLE
[client-v2] fixed NPE and added test

### LINKED ISSUE #2355: [client-v2] NPE when async requested on operation level
## Description
When Client is configured with `useAsyncRequests(false)` and operation has in settings `com.clickhouse.client.api.ClientConfigProperties#ASYNC_OPERATIONS` set to `true` then operation will fail with NPE inside `com.clickhouse.client.api.Client#runAsyncOperation` because `com.clickhouse.client.api.Client#sharedOperationExecutor` is null.

### Steps to reproduce
1. Create non async client 
2. Call any operation with async = true settings 
3.
### Error Log or Exception StackTrace

```

```

### PR DESCRIPTION
**Pull request by chernser**
## Summary
Fixes #2355 by using default JVM pool in case executor is no specified by client nor client is configured for async operations 

## Checklist
Delete items not relevant to your PR:
- [x] Closes #2355 
- [x] Unit and integration tests covering the common scenarios were added
- [ ] A human-readable description of the changes was provided to include in CHANGELOG
- [ ] For significant changes, documentation in https://github.com/ClickHouse/clickhouse-docs was updated with further explanations or tutorials

### CODE REVIEW

File: client-v2/src/test/java/com/clickhouse/client/insert/InsertTests.java [hunk 1]
```diff
@@ -269,6 +270,33 @@ public void insertRawData() throws Exception {
...
+    @Test(groups = { "integration" }, enabled = true)
+    public void insertRawDataAsync() throws Exception {
+        final String tableName = "raw_data_table_async";
+        final String createSQL = "CREATE TABLE " + tableName +
+                " (Id UInt32, event_ts Timestamp, name String, p1 Int64, p2 String) ENGINE = MergeTree() ORDER BY ()";
+
+        initTable(tableName, createSQL);
+
+        InsertSettings localSettings = new InsertSettings(settings.getAllSettings());
+        localSettings.setOption(ClientConfigProperties.ASYNC_OPERATIONS.getKey(), true);
```
Comment (mzitnik) [inline client-v2/src/test/java/com/clickhouse/client/insert/InsertTests.java:282]: Can we also have a test with async disabled

**Review by mzitnik — APPROVED** [review]
