### PR TITLE
Reset roles by "SET ROLE NONE"

### LINKED ISSUE #1647: Add resseting memorized roles
### Describe the bug
After implementing memorized roles (https://github.com/ClickHouse/clickhouse-java/pull/1569) there is no way to reset (forget) roles that were set. 

`SET ROLE NONE` will cause adding `?role=NONE` what is invalid parameter value.

### PR DESCRIPTION
**Pull request by chernser**
## Summary
Closes #1647

## Checklist
Delete items not relevant to your PR:
- [x] Unit and integration tests covering the common scenarios were added
- [x] A human-readable description of the changes was provided to include in CHANGELOG

### CODE REVIEW

**Comment by slvrtrn** [comment]
The following simulation of an app with the impersonation feature based on row policies could be an OK integration test.

Setup:

```sql
CREATE OR REPLACE TABLE test_table
(
    `s` String
)
ENGINE = MergeTree
ORDER BY tuple();
INSERT INTO test_table VALUES ('a'), ('b');

CREATE USER test_user NOT IDENTIFIED;
CREATE ROLE row_a;
CREATE ROLE row_b;
GRANT row_a, row_b TO test_user;

GRANT SELECT ON default.test_table TO test_user;
CREATE ROW POLICY OR REPLACE policy_row_b ON test_table FOR SELECT USING s = 'b' TO row_b;
CREATE ROW POLICY OR REPLACE policy_row_a ON test_table FOR SELECT USING s = 'a' TO row_a;
```
Test:

```
➜ curl -H "Authorization: Basic dGVzdF91c2VyOg==" "http://localhost:8123" --data-binary "SELECT * FROM test_table"
a
b
➜ curl -H "Authorization: Basic dGVzdF91c2VyOg==" "http://localhost:8123?role=row_b" --data-binary "SELECT * FROM test_table"
b
➜ curl -H "Authorization: Basic dGVzdF91c2VyOg==" "http://localhost:8123?role=row_a" --data-binary "SELECT * FROM test_table"
a
➜ curl -H "Authorization: Basic dGVzdF91c2VyOg==" "http://localhost:8123?role=row_a&role=row_b" --data-binary "SELECT * FROM test_table"
a
b
```

In Java code, that could be: 

```
-- no roles set - a select query will get both rows A and B
SET ROLE row_a;
-- gets only row A
SET ROLE row_b;
-- gets both rows A and B
SET ROLE NONE;
-- gets both rows A and B
SET ROLE row_b;
-- gets only row B
```

File: clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/AccessManagementTest.java [hunk 1]
```diff
@@ -106,4 +102,80 @@ private String getServerVersion(Connection connection) {
...
     }
+
+    @Test
+    public void testSetRolesAccessingTableRows() throws SQLException {
+        String httpEndpoint = "http://" + getServerAddress(ClickHouseProtocol.HTTP) + "/";
+        String url = String.format("jdbc:ch:%s", httpEndpoint);
+        Properties properties = new Properties();
+        properties.setProperty(ClickHouseHttpOption.REMEMBER_LAST_SET_ROLES.getKey(), "true");
+        properties.setProperty(ClickHouseHttpOption.CONNECTION_PROVIDER.getKey(),
+                HttpConnectionProvider.APACHE_HTTP_CLIENT.name());
```
Comment (mzitnik) [inline clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/AccessManagementTest.java:113]: Why we are setting this, it is the default

**Review by mzitnik — APPROVED** [review]

File: clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/AccessManagementTest.java (hunk 1 above)
Comment (chernser) [reply clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/AccessManagementTest.java:113]: I've forgot this after testing. Will remove.

**Review by slvrtrn — APPROVED** [review]
