### PR TITLE
[jdbc-v2] Fixes in the PreparedStatementImpl class, the initial length of the parameters is incorrectly changed in the clearParameters method

### LINKED ISSUE #2299: In the PreparedStatementImpl class, the initial length of the parameters is incorrectly changed in the clearParameters method
### Describe the bug

当使用druid连接池时，connection每次close后，会归还连接池，同时，如果connection中的preparedStatement 也需要被池化的时候（由参数druid.maxOpenPreparedStatements决定），会调用clickhouse.PreparedStatementImpl#clearParameters方法，导致初始参数数组的个数多1，最终生成的sql后加了null字符串，引起sql编译错误。

When using a druid connection pool, the connection pool is returned after each close, and clickhouse.PreparedStatementImpl#clearParameters method is called if the preparedStatement in the connection also needs to be pooled (determined by the druid.maxOpenPreparedStatements parameter).  the number of initial parameter arrays is increased by 1, and the final generated SQL is added with a null string, which causes SQL compilation errors.

You can focus on the DruidPooledConnection.closePoolableStatement source code
Image

clickhouse.PreparedStatementImpl constructor

```java
    public PreparedStatementImpl(ConnectionImpl connection, String sql) throws SQLException {
        super(connection);
        this.originalSql = sql;
        //Split the sql string into an array of strings around question mark tokens
        this.sqlSegments = sql.split("\\?");

        //Create an array of objects to store the parameters
        if (originalSql.contains("?")) {
            int count = originalSql.length() - originalSql.replace("?", "").length();
            // 每次 new PreparedStatementImpl 之后，parameters数组的初始长度是正确的参数个数
            // After each new PreparedStatementImpl, the initial length of the parameters array is the correct number of parameters
            this.parameters = new Object[count];
        } else {
            this.parameters = new Object[0];
        }
    }
```

clickhouse.PreparedStatementImpl clearParameters method

```java
    public void clearParameters() throws SQLException {
        checkClosed();
        if (originalSql.contains("?")) {
            // 调用clearParameters方法后，重置parameters数组，此时，数组的初始长度变为sqlSegments.length，比正确的参数个数 + 1
          //  After calling the clearParameters method, reset the parameters array, and the initial length of the array becomes sqlSegments.length, which is more than the correct number of parameters + 1
            this.parameters = new Object[sqlSegments.length];
            // int count = originalSql.length() - originalSql.replace("?", "").length();
            //  this.parameters = new Object[count];
            // sqlSegments.length is 1 more than count
        } else {
            this.parameters = new Object[0];
        }
    }
```

#### Environment
* Client version:  Latest jdbc v2
* Language version: java
* OS:

### PR DESCRIPTION
**Pull request by CCweixiao**
## Summary

Closes https://github.com/ClickHouse/clickhouse-java/issues/2299
## Checklist
Delete items not relevant to your PR:
- [ ] Closes #<issue ref>
- [ ] Unit and integration tests covering the common scenarios were added
- [ ] A human-readable description of the changes was provided to include in CHANGELOG
- [ ] For significant changes, documentation in https://github.com/ClickHouse/clickhouse-docs was updated with further explanations or tutorials

### CODE REVIEW

**Comment by chernser** [comment]
Good day, @CCweixiao! 
Thank you for the contribution! 
Would you please add at least one test to verify the problem is fixed? 

Thanks!

**Comment by CCweixiao** [comment]
> Good day, @CCweixiao! Thank you for the contribution! Would you please add at least one test to verify the problem is fixed?
> 
> Thanks!

Thanks a lot for the code review, I've submitted a test case for the corresponding code fix, please help me review again.

File: jdbc-v2/src/test/java/com/clickhouse/jdbc/PreparedStatementTest.java [hunk 1]
```diff
@@ -491,4 +491,68 @@ void testStatementSplit() throws Exception {
...
+            checkClosed();
+            if (originalSql.contains("?")) {
+                this.parameters = new Object[sqlSegments.length];
+            } else {
+                this.parameters = new Object[0];
+            }
+        }
+
+        @Override
+        String compileSql(String[] segments) {
```
Comment (chernser) [inline jdbc-v2/src/test/java/com/clickhouse/jdbc/PreparedStatementTest.java:547]: this is not a good practice - if someone change an original method then test will not be verifying a production code. 
Please just make `compileSql` package private. This is ok because tests sometimes need to do so.

File: jdbc-v2/src/test/java/com/clickhouse/jdbc/PreparedStatementTest.java [hunk 2]
```diff
@@ -491,4 +491,68 @@ void testStatementSplit() throws Exception {
...
+            ps2.setString(1, "testId");
+            ps2.setString(2, "testName");
+            ps2.setInt(3, 18);
+
+            String compiledSql2 = ps2.compileSql(ps2.sqlSegments);
+            Assert.assertEquals(compiledSql2, "insert into `test_issue_2299` (`id`, `name`, `age`) values ('testId', 'testName', 18)null");
+        }
+    }
+
+    static class TestPreparedStatementImpl extends PreparedStatementImpl {
```
Comment (chernser) [inline jdbc-v2/src/test/java/com/clickhouse/jdbc/PreparedStatementTest.java:530]: please remove this class.

**Comment by chernser** [comment]
@CCweixiao thanks! 
I've reviewed - please see my comments.

**Comment by CCweixiao** [comment]
> @CCweixiao thanks! I've reviewed - please see my comments.

Your suggestion was taken and the test case modifications were completed @chernser

**Comment by mzitnik** [comment]
@CCweixiao can you sign the CLA

**Comment by CCweixiao** [comment]
> @CCweixiao can you sign the CLA

image

**Review by chernser — APPROVED** [review]

**Comment by chernser** [comment]
Good day, @CCweixiao ! 

Would you please try signing CLA once again? 
Sorry for asking after so long time. 

Thanks!

**Comment by CCweixiao** [comment]
> Good day, @CCweixiao !
> 
> Would you please try signing CLA once again? Sorry for asking after so long time.
> 
> Thanks!

It seems I need to change my commit username and email. I didn't pay attention when submitting before. How should I handle this? Should I bring up a new PR?

**Comment by chernser** [comment]
Yes, 
 I think new PR will trigger same check and we do not need to merge it - just simple change. 
 
Thank you!
