### PR TITLE
[jdbc-v2] Antlr4 parser

### LINKED ISSUE #2348: PreparedStatement confused ternary `?` with input parameters
### Describe the bug

The ternary `?` in `"select true ? 1 : 0 as foo"` confuses the PreparedStatement mechanism.

#### Working ternary in Statement
```clojure
;; working example of the ternary against a Statement
clj -Sdeps '{:deps {com.clickhouse/clickhouse-jdbc {:mvn/version "0.8.4"}}}'
user=> (let [jdbc-url "jdbc:clickhouse://localhost:8123"
             sql "select true ? 1 : 0 as foo"]
         (with-open [connection (java.sql.DriverManager/getConnection jdbc-url "default" "password")
                     statement (.createStatement connection)]
           (if (.execute statement sql)
             (let [rs (.getResultSet statement)]
               (while (.next rs)
                 (println (.getInt rs "foo"))))
             (println "no results from sql: \n" sql))))
1
nil
```

##### Failing ternary in PreparedStatement with no inputs

```clojure
user=> (let [jdbc-url "jdbc:clickhouse://localhost:8123"
             sql "select false ? 1 : 0 as foo"]
         (with-open [connection (java.sql.DriverManager/getConnection jdbc-url "default" "password")
                     ps (.prepareStatement connection sql)
                     rs (.executeQuery ps)]
           (while (.next rs)
             (println (.getInt rs "foo")))))
Execution error (ServerException) at com.clickhouse.client.api.internal.HttpAPIClientHelper/readError (HttpAPIClientHelper.java:371).
Code: 62. DB::Exception: Syntax error: failed at position 19 ('1'): 1 : 0 as foo. Expected one of: token, Comma, FROM, PREWHERE, WHERE, GROUP BY, WITH, HAVING, WINDOW, QUALIFY, ORDER BY, LIMIT, OFFSET, FETCH, SETTINGS, UNION, EXCEPT, INTERSECT, INTO OUTFILE, FORMAT, ParallelWithClause, PARALLEL WITH, end of query. (SYNTAX_ERROR) (version 25.1.3.23 (official build)) 
```

##### Failing ternary with one input in PreparedStatement

```clojure
user=> (let [jdbc-url "jdbc:clickhouse://localhost:8123"
             sql "select false ? 1 : 0 as foo where 1 = ?"]
         (with-open [connection (java.sql.DriverManager/getConnection jdbc-url "default" "password")
                     ps (doto (.prepareStatement connection sql)
                          (.setInt 1 1))
                     rs (.executeQuery ps)]
           (while (.next rs)
             (println (.getInt rs "foo")))))
Execution error (ServerException) at com.clickhouse.client.api.internal.HttpAPIClientHelper/readError (HttpAPIClientHelper.java:371).
Code: 62. DB::Exception: Syntax error: failed at position 14 ('1'): 1 1 : 0 as foo where 1 = null. Expected one of: OR, AND, IS NOT DISTINCT FROM, IS NULL, IS NOT NULL, BETWEEN, NOT BETWEEN, LIKE, ILIKE, NOT LIKE, NOT ILIKE, REGEXP, IN, NOT IN, GLOBAL IN, GLOBAL NOT IN, MOD, DIV, alias, AS, identifier, token, Comma, FROM, PREWHERE, WHERE, GROUP BY, WITH, HAVING, WINDOW, QUALIFY, ORDER BY, LIMIT, OFFSET, FETCH, SETTINGS, UNION, EXCEPT, INTERSECT, INTO OUTFILE, FORMAT, ParallelWithClause, PARALLEL WITH, end of query. (SYNTAX_ERROR) (version 25.1.3.23 (official build)) 
user=> 
```

##### Working example with `clickhouse.jdbc.v1=true`

```clojure
❯ clj -Sdeps '{:deps {com.clickhouse/clickhouse-jdbc {:mvn/version "0.8.4"}}}' -J-Dclickhouse.jdbc.v1=true
user=> (let [jdbc-url "jdbc:clickhouse://localhost:8123"
             sql "select false ? 1 : 0 as foo where 1 = ?"]
         (with-open [connection (java.sql.DriverManager/getConnection jdbc-url "default" "password")
                     ps (doto (.prepareStatement connection sql)
                          (.setInt 1 1))
                     rs (.executeQuery ps)]
           (while (.next rs)
             (println (.getInt rs "foo")))))
0
nil
```

### Expected behaviour
These queries should all complete

### Code example
```java
// should be easily translatable from the raw sql strings above.
"select true ? 1 : 0 as foo"
"select false ? 1 : 0 as foo where 1 = ?"
```
#### Environment
* Client version: 0.8.4
* Language version: ?
* OS: osx

#### ClickHouse server
* ClickHouse Server version:
* ClickHouse Server non-default settings, if any:
* 
```
docker run -p8123:8123 -p9000:9000 -e"CLICKHOUSE_PASSWORD=password" -it --rm clickhouse/clickhouse-server:latest
```

### PR DESCRIPTION
**Pull request by chernser**
## Summary

- Replaces custom SQL parsing logic with Antlr4 parse. (because CH repo has grammar for it and easy to use)
- Reimplement several checks using parser
- Does a small cleanup of some utility methods   

Closes https://github.com/ClickHouse/clickhouse-java/issues/2348
Closes https://github.com/ClickHouse/clickhouse-java/issues/2325
Closes https://github.com/ClickHouse/clickhouse-java/issues/2283
Closes https://github.com/ClickHouse/clickhouse-java/issues/2354

## Checklist
Delete items not relevant to your PR:
- [ ] Closes #2348, #2325, #2283
- [ ] Unit and integration tests covering the common scenarios were added
- [ ] A human-readable description of the changes was provided to include in CHANGELOG
- [ ] For significant changes, documentation in https://github.com/ClickHouse/clickhouse-docs was updated with further explanations or tutorials

### CODE REVIEW

File: jdbc-v2/src/main/java/com/clickhouse/jdbc/PreparedStatementImpl.java [hunk 1]
```diff
@@ -59,69 +67,74 @@ public class PreparedStatementImpl extends StatementImpl implements PreparedStat
...
-            if (i < parameters.length) {
-                sb.append(parameters[i]);
-            }
+    private String buildSQL() {
+        StringBuilder compiledSql = new StringBuilder(originalSql);
+        int posOffset = 0;
+        int[] positions = parsedPreparedStatement.getParamPositions();
+        for (int i = 0; i < argCount; i++) {
+            int p = positions[i] + posOffset;
+            String val = values[i].toString();
```
[the remark this answers is not in the document]
Comment (chernser) [reply jdbc-v2/src/main/java/com/clickhouse/jdbc/PreparedStatementImpl.java:121]: Very good point. Added tests for this case.

File: jdbc-v2/src/main/antlr4/com/clickhouse/jdbc/internal/ClickHouseLexer.g4 [hunk 2]
```diff
@@ -0,0 +1,300 @@
+
```
Comment (mzitnik) [inline jdbc-v2/src/main/antlr4/com/clickhouse/jdbc/internal/ClickHouseLexer.g4:1]: Can you provide a source(link) for this information

**Review by mzitnik — COMMENTED** [review]
Can we also add some performance tests to measure the time it takes for the parser

**Comment by ethlo** [comment]
This PR is a game-changer! Is there a chance to get this merged in for 0.8.6?

**Comment by mshustov** [comment]
@ethlo yes, it's the main topic for [0.8.6](https://github.com/ClickHouse/clickhouse-java/milestone/31)

File: jdbc-v2/src/main/java/com/clickhouse/jdbc/ConnectionImpl.java [hunk 3]
```diff
@@ -365,16 +374,23 @@ public Statement createStatement(int resultSetType, int resultSetConcurrency, in
...
-                    TableSchema tableSchema = client.getTableSchema(parsedStatement.getTableName(), schema);
-                    if (tableSchema.getColumns().size() == parsedStatement.getArgumentCount()) {
-                        return new WriterStatementImpl(this, sql, tableSchema, parsedStatement);
-                    }
-                }
+        ParsedPreparedStatement parsedStatement = sqlParser.parsePreparedStatement(sql);
+
+        if (parsedStatement.isInsert() && config.isBetaFeatureEnabled(DriverProperties.BETA_ROW_BINARY_WRITER)) {
+            /*
+             * RowBinary can be used when
```
[the remark this answers is not in the document]
Comment (chernser) [reply jdbc-v2/src/main/java/com/clickhouse/jdbc/ConnectionImpl.java:381]: Yes we can.

File: jdbc-v2/src/main/antlr4/com/clickhouse/jdbc/internal/ClickHouseLexer.g4 (hunk 2 above)
Comment (chernser) [reply jdbc-v2/src/main/antlr4/com/clickhouse/jdbc/internal/ClickHouseLexer.g4:1]: Sorry did not get the question - what information?

Comment (mzitnik) [reply jdbc-v2/src/main/antlr4/com/clickhouse/jdbc/internal/ClickHouseLexer.g4:1]: Where did you take all the definitions

**Review by mzitnik — APPROVED** [review]
