### PR TITLE
[jdbc] Fix prepared statement impl

### LINKED ISSUE #2391: [jdbc] Parsing statement containing `WITH` clause fails on client side
## Description
0.8.6 Patch broke parameter parsing in WITH block
I think it's related to this: https://github.com/ClickHouse/clickhouse-java/pull/2351

### Code Example
```java
    @Test
    void test_parameters() throws SQLException {
        String sql = """
            WITH
                toDateTime(?) AS target_time
            SELECT *
            FROM table
            """;
        assertEquals(1, new ConnectionImpl(host, properties)
            .prepareStatement(sql)
            .getParameterMetaData()
            .getParameterCount());
    } // pass
``` 

```java
    @Test
    void test_parameters() throws SQLException {
        String sql = """
            WITH
                toDateTime(?) AS target_time,
                select 1 as gr
            SELECT *
            FROM table
            """;
        assertEquals(1, new ConnectionImpl(host, properties)
            .prepareStatement(sql)
            .getParameterMetaData()
            .getParameterCount());
    } // 0.8.5 - pass, 0.8.6 - fail

#### Environment
* [ ] Cloud
* Client version: 0.8.6
* Language version: java
* OS: MacOs

#### ClickHouse Server
* ClickHouse Server version:
* ClickHouse Server non-default settings, if any:
* `CREATE TABLE` statements for tables involved:
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary

### PR DESCRIPTION
**Pull request by chernser**
## Summary

- Improves test coverage for the PreparedStatementImpl
- Adds missing check that all parameters are set before executing a query 
- Does simple type cast. Further work will be done later 

Closes https://github.com/ClickHouse/clickhouse-java/issues/2418
Closes #2391 
## Checklist
Delete items not relevant to your PR:
- [x] Closes #<issue ref>
- [x] Unit and integration tests covering the common scenarios were added
- [ ] A human-readable description of the changes was provided to include in CHANGELOG
- [ ] For significant changes, documentation in https://github.com/ClickHouse/clickhouse-docs was updated with further explanations or tutorials

### CODE REVIEW

File: client-v2/src/main/java/com/clickhouse/client/api/DataTypeUtils.java [hunk 1]
```diff
@@ -20,17 +20,19 @@ public class DataTypeUtils {
     /**
      * Formatter for the DateTime type.
      */
-    public static DateTimeFormatter DATETIME_FORMATTER = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
+    public static DateTimeFormatter DATETIME_FORMATTER = DateTimeFormatter.ofPattern("uuuu-MM-dd HH:mm:ss");
```
Comment (mzitnik) [inline client-v2/src/main/java/com/clickhouse/client/api/DataTypeUtils.java:23]: Do you have a link or explanation for doing that, since you do not see that so often (using the format with uuuu)

File: jdbc-v2/src/main/java/com/clickhouse/data/Tuple.java [hunk 2]
```diff
@@ -37,4 +39,22 @@ public String toString() {
         }
         return output;
     }
+
+
+    @Override
+    public boolean equals(Object obj) {
+        if (this == obj) {
```
Comment (mzitnik) [inline jdbc-v2/src/main/java/com/clickhouse/data/Tuple.java:46]: Let's check if obj is null

File: jdbc-v2/src/main/java/com/clickhouse/jdbc/PreparedStatementImpl.java [hunk 3]
```diff
@@ -112,23 +119,27 @@ public PreparedStatementImpl(ConnectionImpl connection, String sql, ParsedPrepar
...
+    private String buildSQL() throws SQLException {
         StringBuilder compiledSql = new StringBuilder(originalSql);
         int posOffset = 0;
         int[] positions = parsedPreparedStatement.getParamPositions();
         for (int i = 0; i < argCount; i++) {
             int p = positions[i] + posOffset;
             String val = values[i];
-            compiledSql.replace(p, p+1, val == null ? "NULL" : val);
-            posOffset += val == null ? 0 : val.length() - 1;
+            if (val == null) {
```
Comment (mzitnik) [inline jdbc-v2/src/main/java/com/clickhouse/jdbc/PreparedStatementImpl.java:129]: A remark for before and after the string will be great here

File: jdbc-v2/src/test/java/com/clickhouse/jdbc/PreparedStatementTest.java [hunk 4]
```diff
@@ -1156,5 +1260,160 @@ public void testWithInClause() throws Exception {
...
+                   }
+               }
+            }
+        }
+    }
+
+    @DataProvider(name = "testTypeCastsDP")
+    public static Object[][] testTypeCastsDP() {
+        return new Object[][] {
+                {100, ClickHouseDataType.Int8, ClickHouseDataType.Int8},
```
Comment (mzitnik) [inline jdbc-v2/src/test/java/com/clickhouse/jdbc/PreparedStatementTest.java:1291]: {100, ClickHouseDataType.Int8, ClickHouseDataType.Int8} according to method signutare `testTypeCastsWithoutArgument(Object value, SQLType targetType, ClickHouseDataType expectedType)`
SQLType targetType -> ClickHouseDataType expectedType)
I'm missing something here

File: client-v2/src/main/java/com/clickhouse/client/api/DataTypeUtils.java (hunk 1 above)
Comment (chernser) [reply client-v2/src/main/java/com/clickhouse/client/api/DataTypeUtils.java:23]: `y` if for year in era and `u` is for just year.

File: jdbc-v2/src/main/java/com/clickhouse/data/Tuple.java (hunk 2 above)
Comment (chernser) [reply jdbc-v2/src/main/java/com/clickhouse/data/Tuple.java:46]: ok. The null check is done on `obj instanceof Tuple`.

File: jdbc-v2/src/main/java/com/clickhouse/jdbc/PreparedStatementImpl.java (hunk 3 above)
Comment (chernser) [reply jdbc-v2/src/main/java/com/clickhouse/jdbc/PreparedStatementImpl.java:129]: Previously we did not check if all parameters are set. This change just moved lines 122 and 123 below the check. 
`val` is null only when we have not set any value. NULL will be a "NULL" string.

File: jdbc-v2/src/test/java/com/clickhouse/jdbc/PreparedStatementTest.java (hunk 4 above)
Comment (chernser) [reply jdbc-v2/src/test/java/com/clickhouse/jdbc/PreparedStatementTest.java:1291]: I've made `ClickHouseDataType` to implement `SQLType` what is valid according to the spec. 
I do always convert any type to `ClickHouseDataType`. In this case first `ClickHouseDataType.Int8` acts as some `SQLType` instance. The second `ClickHouseDataType.Int8` used to check if name of the type returned correctly. For that I use `toTypeName` function.

**Review by mzitnik — APPROVED** [review]
